name: med_agent_mobile
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  side_effect_bloc:
    path: side_effect_bloc
  auto_route: ^7.8.4
  flutter_bloc: ^8.0.1
  intl_utils: ^2.8.7
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  flutter_screenutil: ^5.0.0
  cloud_firestore: ^4.4.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0
  get: ^4.6.5 
  permission_handler: ^11.3.1
  injectable: ^2.3.2
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  either_dart: ^1.0.0
  dio: ^5.4.1
  json_annotation: ^4.6.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.0
  pretty_dio_logger: ^1.1.1
  expandable: ^5.0.1
  auto_size_text_field: ^2.2.2
  collection: ^1.18.0
  slide_switcher: ^1.1.2
  cached_network_image: ^3.3.1
  mask_text_input_formatter: ^2.9.0
  bloc: ^8.1.3
  image_picker: ^0.8.7
  extended_wrap: ^0.1.5
  provider: ^6.1.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  syncfusion_flutter_charts: ^25.1.35
  path_provider: ^2.1.3
  # connectivity_plus: ^6.0.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_crashlytics: ^3.4.18
  flutter_local_notifications: ^17.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_bluetooth_serial: ^0.4.0
  pedometer: ^4.0.1
  flutter_blue_plus: ^1.32.7
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^6.2.0
  build_runner: ^2.1.11
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.2.0

flutter_launcher_icons:
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/
  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlegreyaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/AlegreyaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlegreyaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: AlegreyaSansSC
      fonts:
        - asset: assets/fonts/AlegreyaSansSC-Light.ttf
          weight: 300
        - asset: assets/fonts/AlegreyaSansSC-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/AlegreyaSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlegreyaSansSC-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/AlegreyaSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlegreyaSansSC-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AlegreyaSansSC-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSansSC-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSansSC-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSansSC-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        

